version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-progress

  build:
    commands:
      - echo "Building Lambda functions..."
      - mkdir -p lambda-builds
      - |
        for dir in infra/lambda/*/; do
          if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
            name=$(basename "$dir")
            echo "Building Lambda function: $name"
            (cd "$dir" && npm ci --prefer-offline --no-progress && zip -r "../../lambda-builds/${name}.zip" . -x "*.git*" "node_modules/.cache/*")
          fi
        done
      - echo "Lambda builds complete"
      - ls -lh lambda-builds/

artifacts:
  files:
    - "lambda-builds/*.zip"
  name: BackendBuildOutput

cache:
  paths:
    - "~/.npm/**/*"

