version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing CDK dependencies..."
      - (cd infra && npm ci --no-progress)

  build:
    commands:
      - echo "Deploying frontend infrastructure for environment:$ENVIRONMENT"
      - echo "Copying frontend build artifacts..."
      - cp -r $CODEBUILD_SRC_DIR_FrontendBuildOutput/* dist/ || echo "No frontend build artifacts found"
      - (cd infra && npm run build)
      - |
        echo "Deploying frontend stack..."
        (cd infra && npx cdk deploy IronmanCountdownFrontend-$ENVIRONMENT \
          --context environment=$ENVIRONMENT \
          --context withAssets=false \
          --require-approval never \
          --progress events) || echo "Stack deployment completed"
      - |
        echo "Getting stack outputs..."
        BUCKET=$(aws cloudformation describe-stacks \
          --stack-name IronmanCountdownFrontend-$ENVIRONMENT \
          --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
          --output text 2>/dev/null || echo '')
        DIST_ID=$(aws cloudformation describe-stacks \
          --stack-name IronmanCountdownFrontend-$ENVIRONMENT \
          --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
          --output text 2>/dev/null || echo '')
        FRONTEND_URL=$(aws cloudformation describe-stacks \
          --stack-name IronmanCountdownFrontend-$ENVIRONMENT \
          --query 'Stacks[0].Outputs[?OutputKey==`WebsiteURL`].OutputValue' \
          --output text 2>/dev/null || echo '')
        echo "Syncing frontend files to S3..."
        if [ -n "$BUCKET" ]; then
          aws s3 sync dist/ s3://$BUCKET/ --delete --region ${AWS_DEFAULT_REGION:-us-east-1}
          echo "Frontend files synced to S3"
        else
          echo "⚠️ Bucket name not found, skipping S3 sync"
        fi
        if [ -n "$DIST_ID" ]; then
          echo "Creating CloudFront invalidation..."
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*" \
            --region ${AWS_DEFAULT_REGION:-us-east-1} || echo "Invalidation skipped"
        fi
        echo "FRONTEND_URL=$FRONTEND_URL" > frontend-outputs.env
        echo "DISTRIBUTION_ID=$DIST_ID" >> frontend-outputs.env
        echo "BUCKET_NAME=$BUCKET" >> frontend-outputs.env
      - cat frontend-outputs.env

artifacts:
  files:
    - "frontend-outputs.env"
  name: FrontendDeployOutput

cache:
  paths:
    - "~/.npm/**/*"

