version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-progress || true

  build:
    commands:
      - |
        echo "Running health checks for environment:$ENVIRONMENT"
        API_URL=$(aws cloudformation describe-stacks \
          --stack-name IronmanCountdownApi-$ENVIRONMENT \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
          --output text 2>/dev/null || echo '')
        FRONTEND_URL=$(aws cloudformation describe-stacks \
          --stack-name IronmanCountdownFrontend-$ENVIRONMENT \
          --query 'Stacks[0].Outputs[?OutputKey==`WebsiteURL`].OutputValue' \
          --output text 2>/dev/null || echo '')
        echo "API URL:$API_URL"
        echo "Frontend URL:$FRONTEND_URL"
        if [ -n "$API_URL" ]; then
          echo "Checking API health endpoint..."
          curl -f "$API_URL/health" || echo "⚠️ API health check failed"
        fi
        if [ -n "$FRONTEND_URL" ]; then
          echo "Checking frontend availability..."
          curl -f "$FRONTEND_URL" || echo "⚠️ Frontend health check failed"
        fi
        echo "Health checks completed"

artifacts:
  files:
    - "**/*"
  name: HealthCheckOutput

cache:
  paths:
    - "~/.npm/**/*"

