version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: latest
      python: latest
    commands:
      - echo "Installing CDK dependencies..."
      - (cd infra && npm ci --no-progress)
      - echo "Installing Checkov..."
      - pip3 install checkov --quiet

  build:
    commands:
      - echo "Building infrastructure code..."
      - (cd infra && npm run build)
      - echo "Synthesizing CloudFormation templates..."
      - (cd infra && npx cdk synth --context withAssets=false --all)
      - echo "Running Checkov security scan..."
      - checkov -d infra/cdk.out --quiet || echo "⚠️ Checkov scan completed"

artifacts:
  files:
    - "infra/cdk.out/**/*"
  name: IacSynthOutput

cache:
  paths:
    - "~/.npm/**/*"
    - "~/.cache/pip/**/*"

